dist: xenial

language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get -y install unzip

go_import_path: github.com/OpenLiberty/open-liberty-operator

services:
  - docker

cache:
  directories:
    - vendor

stages:
  - name: build
  - name: unit test
  - name: e2e test

jobs:
 include:
  - name: Build docker image
    stage: build
    script:
    - make build-image
  - name: Run unit tests
    stage: unit test
    script:
    - make unit-test
  - name: Run end-to-end tests
    stage: e2e test
    script:
    - travis_wait 30 make test-e2e
