apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: olo-manager-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: olo-controller-manager
  namespace: olo-ns

